export const fieldLabels: Record<string, string> = {
  titleLine1: "السطر الأول من العنوان",
  titleLine2: "السطر الثاني من العنوان",
  subtitle: "العنوان الفرعي",
  eyebrow: "الشارة العلوية (Eyebrow)",
  title: "العنوان",
  description: "الوصف",
  bookNow: "نص زر احجز موعدك",
  exploreServices: "نص زر استكشف خدماتنا",
  callUs: "نص زر اتصل بنا",
  cta: "نص زر الدعوة لإجراء",
  readMore: "نص زر اقرأ المزيد",
  badgeTitle: "عنوان الشارة",
  badgeSubtitle: "وصف الشارة",
  beforeLabel: "عنوان \"قبل المنظار\"",
  afterLabel: "عنوان \"بعد المنظار\"",
  viewAll: "نص زر مشاهدة الكل",
  contactUs: "نص زر تواصل معنا",
  whatsapp: "نص زر واتساب",
  playAria: "نص زر التشغيل (لذوي الاحتياجات)",
  closeAria: "نص زر الإغلاق (لذوي الاحتياجات)",
  applicationsLabel: "عنوان قائمة دواعي الاستخدام",
  bookBtn: "نص زر احجز استشارة",
  verifiedBadge: "نص شارة \"مريض مؤكد\"",
  doctorResponseLabel: "عنوان \"رد الدكتور\"",
  readTimeLabel: "تسمية دقائق القراءة",
  readMoreLabel: "نص زر اقرأ المزيد",
  quote: "نص الاقتباس",
  signatureName: "اسم التوقيع",
  signatureTitle: "المسمى الوظيفي بالتوقيع",
  servicesBtn: "نص زر خدماتنا",
  contactBtn: "نص زر تواصل معنا",
  titleHighlight: "العنوان المميز (باللون)",
  thumbnailUrl: "صورة الفيديو (Thumbnail)",
  videoUrl: "ملف الفيديو",
  imageUrl: "الصورة",
  formEyebrow: "شارة الفورم",
  formTitle: "عنوان الفورم",
  formDescription: "وصف الفورم",
  formSubmitBtn: "نص زر إرسال الفورم",
  infoEyebrow: "شارة معلومات التواصل",
  infoTitle: "عنوان معلومات التواصل",
  infoDescription: "وصف معلومات التواصل",
  phoneLabel: "تسمية رقم الهاتف",
  whatsappLabel: "تسمية الواتساب",
  emailLabel: "تسمية البريد الإلكتروني",
  addressLabel: "تسمية العنوان",
  followUsLabel: "تسمية \"تابعنا\"",
  categoryEndoscopy: "تسمية تصنيف: مناظير",
  categoryLiver: "تسمية تصنيف: صحة الكبد",
  categoryPrevention: "تسمية تصنيف: نصائح وقاية",
  categoryDigestive: "تسمية تصنيف: الجهاز الهضمي",
  year: "السنة",
  place: "مكان العمل",
  procedure: "الإجراء الطبي",
  date: "التاريخ",
  highlight: "عنوان مختصر",
  doctorResponse: "رد الدكتور",
  value: "الرقم",
  suffix: "لاحقة الرقم (مثال: +)",
  duration: "مدة الفيديو (مثال: 03:12)",
  category: "التصنيف",
  readTime: "دقائق القراءة",
  featured: "مقال رئيسي (Featured)",
  content: "محتوى المقال الكامل",
  rating: "التقييم (من 5)",
  phase: "المرحلة",
  anchor: "الرابط الداخلي",
  applications: "دواعي الاستخدام",
  logoUrl: "الشعار (Logo)",
  name: "الاسم (الكبير)",
  nameEn: "الاسم الفرعي (الصغير)",
  bookHref: "رابط زر احجز موعدك",
  showBookButton: "إظهار زر احجز موعدك",
  showLanguageSwitcher: "إظهار مبدل اللغة",
  openMenu: "نص زر فتح القائمة (لذوي الاحتياجات)",
  tagline: "الوصف تحت الشعار",
  heading: "عنوان العمود",
  rights: "نص حقوق النشر",
  showPhone: "إظهار رقم الهاتف",
  showEmail: "إظهار البريد الإلكتروني",
  showAddress: "إظهار العنوان",
  showCredit: "إظهار شارة الشركة المطورة",
  creditName: "اسم الشركة المطورة",
  creditLabel: "نص شارة الشركة المطورة",
  creditUrl: "رابط الشركة المطورة",
  creditLogoUrl: "شعار الشركة المطورة",
};

export function labelize(key: string): string {
  return fieldLabels[key] ?? key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
}
